### ISSUE TITLE
Possible bug when generating code for "to_many" associations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/graphql-server-model-codegen#73]
When trying to generate the `graphql-server` using the latest version of this code-generator with [these data model definitions](https://github.com/ScienceDb/ScienceDbStarterPack/tree/ReconstructDb/data_model_definitions) as input, the following error is thrown:

```
graphql-server-model-codegen --jsonFiles /opt/data_model_definitions/ -o /opt/graphql-server/
Generating files...
Reading... cultivar.json
cultivar
Reading... field_plot.json
field_plot
Reading... individual.json
/usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:459
          associations_info[sql_type].push(assoc);
                                      ^

TypeError: Cannot read property 'push' of undefined
    at /usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:459:39
    at Array.forEach (<anonymous>)
    at parseAssociations (/usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:430:36)
    at Object.module.exports.getOptions (/usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:379:21)
    at /usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:599:33
    at Array.forEach (<anonymous>)
    at Object.module.exports.generateCode (/usr/local/lib/node_modules/graphql-server-model-codegen/funks.js:596:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphql-server-model-codegen/index.js:21:7)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

As the above `Reading... individual.json` indicates the first, in alphabetical order, data model definition is processed that has a `to_many` association. Hence the hypothesis that the `to_many` association causes this error to apear? 

Please fix as soon as possible.

**Comment by vsuaste** [comment]
The error was because _keyIn_ attribute was missing in all the associations in the json description file.
https://scidb-conabio.slack.com/archives/CE5BRGBLZ/p1571843534028200
